name: Cybertronix
description: A job management software written with Flutter.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^2.0.0
  http: '>=0.11.3+12'
  path_provider: ^0.3.0
  intl:
  image_picker: ^0.2.0
  image:
  share: ^0.3.0
  google_sign_in:
  firebase_auth:
  firebase_messaging:
  firebase_storage:
  cloud_firestore: ^0.3.2
  path:
  zoomable_image:
  strings:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter...
flutter:
  assets:
    - assets/hey_ladies.jpg
    - assets/placeholder.jpg

  uses-material-design: true

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. Note: the `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
